### PR TITLE
Support for Power (ppc64le) architecture

### LINKED ISSUE #142: Support for ppc64le architecture
**Is your feature request related to a problem? Please describe.**
Kruize images are available only for Intel architecture. For using kruize on Power, I need to build the images manually.

**Describe the solution you'd like**
ppc64le docker images for kruize to allow running of kruize on ppc64le Kubernetes/OpenShift clusters

### PR DESCRIPTION
**Pull request by pravin-dsilva**
This adds support for ppc64le architecture.

Fixes #142

### CODE REVIEW

**Comment by bpradipt** [comment]
looks like Travis ppc64le build failed to update the repos. This could be due to some intermittent network issues with ppc64le repos.  Can the ppc64le job be restarted ?

**Comment by ShishirH** [comment]
Thank you @pravin-dsilva for the PR!
@dinogun Can you please review this?

**Comment by bpradipt** [comment]
@dinogun anything pending to move this PR ahead ?

**Comment by dinogun** [comment]
@pravin-dsilva @bpradipt Sorry for not getting back sooner, the PR looks good, my only concern is the use of a non-standard prometheus image (`PROMETHEUS_DOCKER_IMAGE="pravindsilva/prometheus-linux-ppc64le:latest"`). So is there no standard prometheus ppc64le image ?

**Comment by pravin-dsilva** [comment]
@dinogun I've built that as currently there isn't any standard/official prometheus ppc64le image. As of now, the docker images in https://hub.docker.com/r/prom/prometheus/ have only amd64 support.

**Comment by bpradipt** [comment]
@pravin-dsilva I think it would be good to have the image in quay.io/powercloud and use the same in the code instead of personal location.

**Comment by pravin-dsilva** [comment]
@bpradipt I've updated the code to use the image from quay.io/powercloud/prometheus-linux-ppc64le:latest which is built from the latest prometheus code.
@dinogun  could you please review? Thanks!

**Review by dinogun — APPROVED** [review]
LGTM!

**Comment by dinogun** [comment]
@pravin-dsilva the PR looks good and I'll merge for now. I would suggest working with upstream prometheus to provide ppc64le images especially as you seem to have got it all working. Thank you for the PR !

**Pull request merged**
